# Generated by Django 6.0.4 on 2026-04-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='specialized_sector',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('fullstack', 'Fullstack'), ('data_science', 'Data Science'), ('mobile', 'Mobile Development')], default='fullstack', max_length=50),
        ),
    ]
