# Generated by Django 6.0.4 on 2026-05-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification_interview'),
        ('jobs', '0003_alter_application_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='jobs.joboffer'),
        ),
    ]
