# Generated by Django 6.0.4 on 2026-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
    ]
