# Generated by Django 6.0.4 on 2026-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('android', 'Android App Development'), ('ios', 'iOS Development'), ('web_app', 'Web App'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('fullstack', 'Fullstack'), ('ui_ux', 'UI/UX Design')], max_length=100),
        ),
    ]
