# Generated by Django 6.0.4 on 2026-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateskill',
            name='proficiency_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='years_of_experience',
            field=models.CharField(choices=[('1', '1 Year'), ('2', '2 Years'), ('3', '3 Years'), ('4', '4 Years'), ('5', '5 Years'), ('6', '6 Years'), ('7', '7 Years'), ('8', '8 Years'), ('9', '9 Years'), ('10', '10 Years'), ('10+', '10+ Years')], max_length=20),
        ),
    ]
