# Generated by Django 6.0.4 on 2026-04-30 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_question_score_and_new_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['sector', 'skill_id', 'set_number', 'question_order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assessment',
            name='score_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='skills.score'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='set_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='score',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='score',
            name='question_set_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('score_record', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('skill', 'set_number', 'question_order')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'candidate_skill', 'attempt_number')},
        ),
    ]
