# Generated by Django 6.0.4 on 2026-04-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sector',
            field=models.CharField(choices=[('android', 'Android App Development'), ('ios', 'iOS Development'), ('web_app', 'Web App'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('fullstack', 'Fullstack'), ('ui_ux', 'UI/UX Design'), ('mobile', 'Mobile Development'), ('data_science', 'Data Science')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('android', 'Android App Development'), ('ios', 'iOS Development'), ('web_app', 'Web App'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('fullstack', 'Fullstack'), ('ui_ux', 'UI/UX Design'), ('mobile', 'Mobile Development'), ('data_science', 'Data Science')], max_length=100),
        ),
    ]
