# Generated by Django 6.0.4 on 2026-05-02

import django.db.models.deletion
from django.db import migrations, models


def seed_progress_for_existing_candidate_skills(apps, schema_editor):
    CandidateSkill = apps.get_model('skills', 'CandidateSkill')
    CandidateSkillProgress = apps.get_model('skills', 'CandidateSkillProgress')

    for candidate_skill in CandidateSkill.objects.all().iterator():
        CandidateSkillProgress.objects.get_or_create(
            candidate_id=candidate_skill.candidate_id,
            skill_id=candidate_skill.skill_id,
            defaults={'add_count': 1},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_alter_question_sector_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_count', models.PositiveSmallIntegerField(default=0)),
                ('total_attempts', models.PositiveSmallIntegerField(default=0)),
                ('total_failures', models.PositiveSmallIntegerField(default=0)),
                ('current_cycle_attempts', models.PositiveSmallIntegerField(default=0)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('times_blocked', models.PositiveSmallIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('penalty_points', models.FloatField(default=0.0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress_records', to='accounts.candidateprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_progress_records', to='skills.skill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
            },
        ),
        migrations.RunPython(seed_progress_for_existing_candidate_skills, migrations.RunPython.noop),
    ]
