# Generated by Django 6.0.4 on 2026-05-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_invitation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='scheduled_time',
            field=models.TimeField(),
        ),
    ]
